const mealList = [
  "Hamburgers",
  "Spaghetti",
  "Tacos",
  "Salad",
  "Soup",
  "Potatoes",
  "Steak",
  "Waffles",
  "Chicken",
  "McDonalds",
  "Cereal",
  "Pancakes",
  "BLTs",
  "Sandwiches",
  "Culvers",
  "Hot Pockets",
  "Pizza",
  "Pizza Rolls",
  "Nachos",
  "Chimichangas",
  "Chicken Pot Pie",
  "Broccoli Soup",
  "Taco Bell",
  "Scrambled Eggs",
  "Eggs Benedict",
  "Fried Rice",
  "Orange Chicken",
  "Pulled Pork Sandwiches",
  "Mac n Cheese",
  "Stuffed Pasta Shells",
  "Chicken Noodle Soup",
  "White Chicken Chili",
  "Clam Chowder",
  "Grilled Cheese",
  "Meatball Sandwiches",
  "French Toast",
  "Crepes",
  "Biscuits and Gravy",
  "Casserole",
  "Tater Tots",
  "Hawaiian Haystacks",
  "Kebabs",
  "Shrimp Fettuccine",
  "Rice and Veggies",
  "Quesadillas",
  "Shepherd's Pie",
];

export default mealList;
